### ISSUE TITLE
Core Dump

### ISSUE THREAD

**Issue by mamumi** [oxagast/oxasploits#1]
I try core dump 
but gdb an error 

```
Attaching to process 40610
[New LWP 40611]
[New LWP 40612]
[New LWP 40613]
[New LWP 40615]
[New LWP 40616]
[New LWP 40801]
[New LWP 40803]
[New LWP 40805]
[New LWP 40806]
[New LWP 40807]
[New LWP 40808]
[New LWP 40809]
[New LWP 40810]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
0x00007ffb02eeccf6 in __GI_ppoll (fds=0x563531ed4808, nfds=2, timeout=<optimized out>, sigmask=0x0) at ../sysdeps/unix/sysv/linux/ppoll.c:39
39	../sysdeps/unix/sysv/linux/ppoll.c: No such file or [directory.]
```

how to clear core dump ubuntu 18

**Comment by oxagast** [comment]
I think the error you're seeing is gdb trying to find the source file ppoll.c from glibc (and failing to find it).  But can you clarify what inside oxasploit's you're working with that is throwing this in gdb?  I'm just not sure what you're working on or trying to do.

Thanks,
Marshall

**Comment by mamumi** [comment]
Hi! Marshall 

I have an old encreypted wallet.dat, i am try have private key from wallet.dat by "makeitrain.sh" 

Thanks 
Mamu

**Comment by oxagast** [comment]
I'm not sure if it works with password protected encrypted wallets as they may not be structured the same (but it may).  I've only tested extracting _unencrypted_ wallets from core dumps.
